-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 16:47:06 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Subscriptions
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Subscriptions` ;
CREATE SCHEMA IF NOT EXISTS `Subscriptions` DEFAULT CHARACTER SET utf8 ;
USE `Subscriptions` ;

-- -----------------------------------------------------
-- Table `Subscriptions`.`DeliveryTiming`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`DeliveryTiming` (
  `deliveryTimingId` INT(11) NOT NULL AUTO_INCREMENT,
  `DeliveryTimingValueHours` INT(11) NOT NULL,
  PRIMARY KEY (`deliveryTimingId`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`DeliveryType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`DeliveryType` (
  `deliveryTypeId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deliveryTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deliveryTypeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`Namespace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`Namespace` (
  `namespaceId` INT(11) NOT NULL AUTO_INCREMENT,
  `Namespace` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`namespaceId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`Subscriber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`Subscriber` (
  `subscriberId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `apiKey` VARCHAR(45) NOT NULL,
  `mobileToken` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`subscriberId`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`SubscriptionDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`SubscriptionDetails` (
  `subscriptionDetailId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `subscriberDeliveryTokenOrUrl` VARCHAR(255) NOT NULL,
  `subscriptionDeliveryDetailsMisc` VARCHAR(1000) NULL DEFAULT NULL,
  `maxRetryCount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`subscriptionDetailId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`Topic` (
  `topicId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespaceId` INT(11) NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `suspended` TINYINT(1) NOT NULL,
  PRIMARY KEY (`topicId`),
  UNIQUE INDEX `topic_UNIQUE` (`topic` ASC),
  INDEX `fk_Topic_Namespace1_idx` (`namespaceId` ASC),
  CONSTRAINT `fk_Topic_Namespace1`
    FOREIGN KEY (`namespaceId`)
    REFERENCES `Subscriptions`.`Namespace` (`namespaceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`Subscription` (
  `subscriptionId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `topicId` BIGINT(20) NOT NULL,
  `subscriberId` BIGINT(20) NOT NULL,
  `deliveryTypeId` BIGINT(20) NOT NULL,
  `deliveryTimingId` INT(11) NOT NULL,
  `subscriptionDetailId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`subscriptionId`, `topicId`, `subscriberId`, `deliveryTypeId`, `deliveryTimingId`, `subscriptionDetailId`),
  UNIQUE INDEX `topicId_UNIQUE` (`topicId` ASC),
  UNIQUE INDEX `subscriberId_UNIQUE` (`subscriberId` ASC),
  UNIQUE INDEX `deliveryTypeId_UNIQUE` (`deliveryTypeId` ASC),
  INDEX `fk_Subscriptions_Topics_idx` (`topicId` ASC),
  INDEX `fk_Subscriptions_Subscribers1_idx` (`subscriberId` ASC),
  INDEX `fk_Subscriptions_SubscriptionDeliveryDetails1_idx` (`subscriptionDetailId` ASC),
  INDEX `fk_Subscription_DeliveryType1_idx` (`deliveryTypeId` ASC),
  INDEX `fk_Subscription_DeliveryTiming1_idx` (`deliveryTimingId` ASC),
  CONSTRAINT `fk_Subscription_DeliveryTiming1`
    FOREIGN KEY (`deliveryTimingId`)
    REFERENCES `Subscriptions`.`DeliveryTiming` (`deliveryTimingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscription_DeliveryType1`
    FOREIGN KEY (`deliveryTypeId`)
    REFERENCES `Subscriptions`.`DeliveryType` (`deliveryTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscriptions_Subscribers1`
    FOREIGN KEY (`subscriberId`)
    REFERENCES `Subscriptions`.`Subscriber` (`subscriberId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscriptions_SubscriptionDeliveryDetails1`
    FOREIGN KEY (`subscriptionDetailId`)
    REFERENCES `Subscriptions`.`SubscriptionDetails` (`subscriptionDetailId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscriptions_Topics`
    FOREIGN KEY (`topicId`)
    REFERENCES `Subscriptions`.`Topic` (`topicId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Subscriptions`.`hibernate_sequences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscriptions`.`hibernate_sequences` (
  `sequence_name` VARCHAR(255) NULL DEFAULT NULL,
  `sequence_next_hi_value` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

/*
-- Query: 
-- Date: 2015-08-20 11:56
*/
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (1,0);
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (2,1);
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (3,3);
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (4,6);
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (5,12);
INSERT INTO `DeliveryTiming` (`deliveryTimingId`,`DeliveryTimingValueHours`) VALUES (6,24);

/*
-- Query: 
-- Date: 2015-08-20 11:56
*/
INSERT INTO `DeliveryType` (`deliveryTypeId`,`deliveryTypeName`) VALUES (1,'PushAPICall');
INSERT INTO `DeliveryType` (`deliveryTypeId`,`deliveryTypeName`) VALUES (2,'iOS');
INSERT INTO `DeliveryType` (`deliveryTypeId`,`deliveryTypeName`) VALUES (3,'GCM');

/*
-- Query: 
-- Date: 2015-08-26 11:25
*/
INSERT INTO `Namespace` (`namespaceId`,`Namespace`,`Description`) VALUES (1,'DSG','DSG');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
